<?php

namespace JoliCode\MediaBundle\Storage;

use JoliCode\MediaBundle\Binary\Binary;
use JoliCode\MediaBundle\Binary\MimeTypeGuesser;
use JoliCode\MediaBundle\Library\Library;
use JoliCode\MediaBundle\Model\MediaVariation;
use JoliCode\MediaBundle\Storage\Strategy\StorageStrategyInterface;
use JoliCode\MediaBundle\Variation\Variation;
use League\Flysystem\Filesystem;
use League\Flysystem\StorageAttributes;
use League\Flysystem\UnableToGenerateTemporaryUrl;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class CacheStorage
{
    private Library $library;

    public function __construct(
        private readonly StorageStrategyInterface $strategy,
        private readonly Filesystem $filesystem,
        private readonly string $urlPath,
        private readonly bool $mustStoreWhenGeneratingUrl,
        private readonly UrlGeneratorInterface $urlGenerator,
        private readonly MimeTypeGuesser $mimeTypeGuesser,
        private readonly MediaVariationPropertyAccessor $mediaVariationPropertyAccessor,
        private readonly bool $storeOnCreate = false,
    ) {
    }

    public function delete(string $path, Variation $variation): void
    {
        $this->deleteFile($this->strategy->getPath($path, $variation));
        $this->mediaVariationPropertyAccessor->clearCache($path, $variation);
    }

    public function deleteDirectory(string $path, Variation $variation): void
    {
        $this->deleteDir($this->strategy->getPath($path, $variation));
    }

    public function deleteDir(string $path): void
    {
        $this->filesystem->deleteDirectory($path);
    }

    public function deleteFile(string $path): void
    {
        $this->filesystem->delete($path);
    }

    public function get(string $path, Variation $variation): Binary
    {
        $mimeType = $this->getMimeType($path, $variation);
        $format = $this->mimeTypeGuesser->getPossibleExtension($mimeType);
        $path = $this->strategy->getPath($path, $variation);

        return new Binary(
            $mimeType,
            $format,
            $this->filesystem->read($path),
            $path,
        );
    }

    public function getFileSize(string $path, Variation $variation): int
    {
        return $this->mediaVariationPropertyAccessor->getFileSize($path, $variation);
    }

    public function getFormat(string $path, Variation $variation): string
    {
        return $this->mediaVariationPropertyAccessor->getFormat($path, $variation);
    }

    public function getMimeType(string $path, Variation $variation): string
    {
        return $this->mediaVariationPropertyAccessor->getMimeType($path, $variation);
    }

    public function getPath(string $path, Variation $variation): string
    {
        return $this->strategy->getPath($path, $variation);
    }

    public function getLibrary(): Library
    {
        return $this->library;
    }

    public function getFilesystem(): Filesystem
    {
        return $this->filesystem;
    }

    public function getMediaVariationPropertyAccessor(): MediaVariationPropertyAccessor
    {
        return $this->mediaVariationPropertyAccessor;
    }

    /**
     * @return false|array{height: int, width: int}
     */
    public function getPixelDimensions(string $path, Variation $variation): array|false
    {
        return $this->mediaVariationPropertyAccessor->getPixelDimensions($path, $variation);
    }

    public function getStrategy(): StorageStrategyInterface
    {
        return $this->strategy;
    }

    /**
     * Generates a pre-signed URL pointing directly at the storage backend, valid
     * until the given expiration date (one hour by default).
     *
     * The variation file is not generated by this method: signing the URL of a
     * variation that has not been stored yet produces a URL to a missing object.
     *
     * @param array<string, mixed> $config extra options forwarded to the filesystem adapter
     *
     * @throws UnableToGenerateTemporaryUrl when unsupported by the configured filesystem adapter
     */
    public function getTemporaryUrl(
        string $path,
        Variation $variation,
        \DateTimeInterface|\DateInterval|null $expiresAt = null,
        array $config = [],
    ): string {
        return $this->filesystem->temporaryUrl(
            $this->strategy->getPath($path, $variation),
            TemporaryUrlExpiration::resolve($expiresAt),
            $config,
        );
    }

    public function getUrl(
        string $path,
        Variation $variation,
        int $referenceType = UrlGeneratorInterface::ABSOLUTE_PATH,
    ): string {
        $parameters = [
            'slug' => $this->strategy->getFilePath($path, $variation),
            'variation' => $variation->getName(),
        ];

        return $this->urlGenerator->generate(
            $this->getRouteName(),
            $parameters,
            $referenceType,
        );
    }

    public function getUrlPath(): string
    {
        return $this->urlPath;
    }

    public function has(string $path, Variation $variation): bool
    {
        return $this->filesystem->has($this->strategy->getPath($path, $variation));
    }

    public function isStored(string $path, Variation $variation): bool
    {
        return $this->mediaVariationPropertyAccessor->isStored($path, $variation);
    }

    /**
     * @return string[]
     */
    public function list(?string $path = null, ?string $contains = null, ?Variation $variation = null): array
    {
        $pathCriterion = '';

        if ($variation instanceof Variation) {
            $pathCriterion = '^' . preg_quote($this->strategy->getPath('', $variation), '/');
            if (null !== $path) {
                $pathCriterion .= '/' . preg_quote((string) $contains, '/');
            }
        } elseif (null !== $path) {
            $pathCriterion .= '^' . preg_quote((string) $contains, '/');
        }

        $listing = $this->filesystem->listContents($path ?? '', true)
            ->filter(static fn (StorageAttributes $attributes): bool => $attributes->isFile())
        ;

        if ('' !== $pathCriterion) {
            // @TODO check rather using the withPath() method
            $listing = $listing->filter(static fn (StorageAttributes $attributes): bool => (bool) preg_match('/' . $pathCriterion . '/', $attributes->path()));
        }

        if (null !== $contains) {
            $listing = $listing->filter(static fn (StorageAttributes $attributes): bool => (bool) preg_match('/' . preg_quote($contains, '/') . '/', $attributes->path()));
        }

        return $listing
            ->map(static fn (StorageAttributes $attributes): string => $attributes->path())
            ->toArray()
        ;
    }

    /**
     * @return string[]
     */
    public function listDirectories(?string $parent = null, ?Variation $variation = null): array
    {
        $path = $this->strategy->getPath($parent ?? '', $variation);

        return $this->filesystem->listContents($path, false)
            ->filter(static fn (StorageAttributes $attributes): bool => $attributes->isDir())
            ->sortByPath()
            ->map(static fn (StorageAttributes $attributes): string => $attributes->path())
            ->toArray()
        ;
    }

    /**
     * @return string[]
     */
    public function listFilePaths(?string $path = null, ?Variation $variation = null): array
    {
        $path = $this->strategy->getPath($path ?? '', $variation);

        return $this->filesystem->listContents($path, false)
            ->filter(static fn (StorageAttributes $attributes): bool => $attributes->isFile())
            ->sortByPath()
            ->map(static fn (StorageAttributes $attributes): string => $attributes->path())
            ->toArray()
        ;
    }

    public function setLibrary(Library $library): void
    {
        $this->library = $library;
    }

    public function store(MediaVariation $mediaVariation): void
    {
        $path = $this->strategy->getPath(
            $mediaVariation->getMedia()->getPath(),
            $mediaVariation->getVariation(),
        );
        $this->mediaVariationPropertyAccessor->clearCache(
            $mediaVariation->getMedia()->getPath(),
            $mediaVariation->getVariation(),
        );
        $this->filesystem->write($path, $mediaVariation->getBinary()->getContent());
    }

    public function mustStoreOnCreate(): bool
    {
        return $this->storeOnCreate;
    }

    public function mustStoreWhenGeneratingUrl(MediaVariation $mediaVariation): bool
    {
        $mustStore = $mediaVariation->getVariation()->mustStoreWhenGeneratingUrl()
            ?? $this->mustStoreWhenGeneratingUrl;

        return $mustStore && !$mediaVariation->isStored();
    }

    private function getRouteName(): string
    {
        return 'joli_media_cache_' . $this->getLibrary()->getName();
    }
}
